name: CI Checks

on:
  push:
    branches:
    - main

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Check out code into the Go module directory
      - uses: actions/checkout@v3
      - name: Run Test
        run: make test
      - name: Coverage Check
        run: make coverage
          
      - name: golangci-lint
        [cite_start]uses: golangci/golangci-lint-action@v3 # รัน Linter อัตโนมัติ [cite: 136]

      - name: Run Unit Tests
        [cite_start]run: go test -v -cover ./... # รัน Test พร้อมตรวจสอบ Code Coverage [cite: 566]